# Generated by Django 2.2.7 on 2019-11-26 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('kh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('km', models.CharField(max_length=50)),
                ('xf', models.SmallIntegerField(default=4)),
                ('xs', models.SmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('yxh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mc', models.CharField(max_length=50)),
                ('dz', models.CharField(max_length=50, null=True)),
                ('lxdh', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('gh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=20)),
                ('xb', models.CharField(max_length=10, null=True)),
                ('csrq', models.DateField(null=True)),
                ('xl', models.CharField(max_length=20, null=True)),
                ('jbgz', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_table',
            fields=[
                ('xh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=30)),
                ('xb', models.CharField(max_length=10, null=True)),
                ('csrq', models.DateField(null=True)),
                ('jg', models.CharField(max_length=30, null=True)),
                ('sjhm', models.CharField(max_length=30, null=True)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='Open_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=50)),
                ('sksj', models.CharField(max_length=50)),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
            ],
            options={
                'unique_together': {('xq', 'kh', 'gh')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.CreateModel(
            name='Option_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pscj', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)])),
                ('kscj', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)])),
                ('zpcj', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)])),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Stu_table')),
                ('xq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Open_lesson')),
            ],
            options={
                'unique_together': {('xh', 'xq', 'kh', 'gh')},
            },
        ),
    ]
