# Generated by Django 2.2.7 on 2019-11-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='open_lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='option_lesson',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='open_lesson',
            index_together={('xq', 'kh', 'gh')},
        ),
        migrations.AlterIndexTogether(
            name='option_lesson',
            index_together={('xh', 'xq', 'kh', 'gh')},
        ),
    ]
