# Generated by Django 2.2.7 on 2019-11-30 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20191130_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_lesson',
            name='kscj',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='option_lesson',
            name='pscj',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='option_lesson',
            name='zpcj',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
