# Generated by Django 2.2.7 on 2019-12-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20191130_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_lesson',
            name='xq',
            field=models.CharField(max_length=50),
        ),
    ]
