# Generated by Django 2.2.7 on 2019-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_login_supersuser_teacher_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
