# Generated by Django 2.2.7 on 2019-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_status',
            name='now',
            field=models.CharField(default='', max_length=5),
        ),
    ]
