# Generated by Django 2.2.7 on 2019-12-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_lesson_status_now'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson_Status',
        ),
    ]
