# Generated by Django 2.2.7 on 2019-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_delete_lesson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='present_semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=50)),
                ('xk', models.CharField(max_length=5)),
                ('dqxq', models.CharField(max_length=5)),
            ],
        ),
    ]
