# Generated by Django 2.2.7 on 2020-01-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_present_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rule_ks',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rule_ps',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
