# Generated by Django 2.2.7 on 2020-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200121_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_semester',
            name='cjxq',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
