# Generated by Django 2.2.7 on 2020-03-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200127_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
            ],
        ),
    ]
