# Generated by Django 2.2.7 on 2020-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_note_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_table',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
