# Generated by Django 2.2.7 on 2020-03-02 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_note_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_table',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
