# Generated by Django 2.2.7 on 2020-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20200303_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Note_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Note_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note_table',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
