# Generated by Django 2.2.7 on 2020-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20200303_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_semester',
            name='xkss',
            field=models.IntegerField(default=30),
        ),
    ]
