# Generated by Django 2.2.7 on 2020-03-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_present_semester_xkss'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_lesson',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
