# Generated by Django 2.2.7 on 2020-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_option_lesson_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_table',
            name='gh',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note_table',
            name='kh',
            field=models.CharField(max_length=20),
        ),
    ]
